version: 2

jobs:
  python3:
    docker:
      - image: circleci/python:3.6.1
    steps:
      - checkout
      - run: wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
      - run: chmod +x miniconda.sh && ./miniconda.sh -b -p ~/miniconda
      - run: export PATH="~/miniconda/bin:$PATH"
      - run: conda update --yes --quiet conda
      - run: conda create -n testenv --yes --quiet python=3.6
      - run: source activate testenv
      - run: conda install --yes pip numpy scipy scikit-learn matplotlib sphinx sphinx_rtd_theme numpydoc
      - run: pip install sphinx-gallery
      - run: pip install .
      - run: cd doc
      - run: make html
      - store_artifacts:
          path: doc/_build/html
          destination: doc
      - store_artifacts:
          path: ~/log.txt
      - persist_to_workspace:
          root: doc/_build/html
          paths: .
      - attach_workspace:
          at: doc/_build/html
      - run: ls -ltrh doc/_build/html
    filters:
      branches:
        ignore: gh-pages

workflows:
  version: 2
  build-doc-and-deploy:
    jobs:
      - python3
